FROM openjdk:8-jdk-alpine
MAINTAINER alex nguyen
EXPOSE 8100
COPY target/currency-conversion-service-v1.0.war currency-conversion-service-v1.0.war
CMD ["java","-jar","/currency-conversion-service-v1.0.war"]